blog/urls.py
from blog.views import PostDetailView, search, PostBlogView, UpdateBlogView, DeleteBlogView, CommentReplyView
from django.urls import path

urlpatterns = [
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post'),
    path('post/<int:post_pk>/comment/<int:pk>/reply', CommentReplyView.as_view(), name='reply'),
    path('post_blog_page/', PostBlogView.as_view(), name='post_blog_page'),
    path('post_blog_page/delete/<int:pk>', DeleteBlogView.as_view(), name='delete_blog_page'),
    path('post_blog_page/update/<int:pk>', UpdateBlogView.as_view(), name='update_blog_page'),
    path('q', search, name='search'),
]

pages/urls.py
from . import views
from django.conf.urls import url
from django.urls import path, re_path
from pages.views import author_profiles, ChangePassword, DevProfileView, home, my_profile, portfolio, update_profile

app_name = 'pages'

urlpatterns = [
    path('', home, name='home'),
    re_path(r'^author_profiles/(?P<id>[0-9]+)/$',
            author_profiles, name='author_profiles'),
    path('change-password/', ChangePassword.as_view(
        template_name='pages/change_password.html'), name='change-password'),
    path('my_profile/', my_profile, name='my_profile'),
    path('my_profile/update/', update_profile, name='update_profile'),
    path('password_success/', views.password_success, name='password_success'),
    path('developer_profile/', DevProfileView.as_view(), name='developer_profile'),
]

shareItBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path( 'admin/', admin.site.urls ),
    path( 'accounts/', include( 'allauth.urls' ) ),
    path( '', include( 'pages.urls', namespace='pages' ) ),
    path( '', include( 'blog.urls' ) ),
    path( 'ckeditor/', include( 'ckeditor_uploader.urls' ) ),
] 
# + static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT ) + static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )
    urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )

templates/pages/author_profile.html
{% extends 'pages/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load hitcount_tags %}

{% block title %} | Author Profile{% endblock title %}

{% block content %}

<section class="h-100 gradient-custom-2">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-10 col-xl-10">
                <div class="card">
                    <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
                        <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                            <img src="{{ profile.avatar.url }}" alt="Generic placeholder image"
                                class="img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">

                            <div class="d-flex justify-content-center mb-2">
                                {% if user.is_authenticated %}
                                {% if user.id == profile.id %}
                                <a href="{% url 'pages:update_profile' %}" type="button" class="btn btn-secondary"
                                    data-mdb-ripple-color="dark" style="z-index: 1;">
                                    Edit profile
                                </a>
                                {% else %}
                                <a href="#" type="button" class="btn btn-primary"
                                    data-mdb-ripple-color="dark" style="z-index: 1;">
                                    Message
                                </a>
                                {% endif %}
                                {% endif %}
                            </div>

                        </div>
                        <div class="ms-3" style="margin-top: 130px;">
                            <h5>{{ profile.first_name }}&nbsp;{{ profile.middle_name }}&nbsp;{{ profile.last_name }}
                            </h5>
                            <p>{{ profile.user }}</p>
                        </div>
                    </div>
                    <div class="p-4 text-black" style="background-color: #f8f9fa;">
                        <div class="d-flex justify-content-end text-center py-1">
                            <div>
                                <p class="mb-1 h5">{{ posts_count }}</p>
                                <p class="small text-muted mb-0"># of Blog Posts</p>
                            </div>
                            <div class="px-3">
                                <p class="mb-1 h5">{{ comment_count }}</p>
                                <p class="small text-muted mb-0"># Comments</p>
                            </div>
                        </div>
                    </div>
                    <div class="card-body p-4 text-black">
                        <div class="mb-5">
                            <p class="lead fw-normal mb-1">About Me</p>
                            <div class="p-4" style="background-color: #f8f9fa;">
                                <p class="font-italic mb-1">{{ profile.bio }}</p>
                            </div>

                            <p class="lead fw-normal mb-1">Email Address</p>
                            <div class="p-4" style="background-color: #f8f9fa;">
                                <p class="font-italic mb-1">{{ profile.user.email }}</p>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mb-4">
                            <p class="lead fw-normal mb-0">My Blog Posts</p>
                        </div>
                        <div class="row g-2">
                            {% if posts %}
                            {% for post in posts %}
                            <div class="col-md-6">
                                <div
                                    class="card border hover-shadow-6 mb-6 d-block bg-image hover-overlay hover-zoom hover-shadow ripple">
                                    {% if post.thumbnail %}
                                    <a href="#"><img class="card-img-top" src="{{ post.thumbnail.url }}"
                                            alt="Card image cap" style="height: 18rem;"></a>
                                    {% else %}
                                    <a href="#"><img class="card-img-top" src="{{ post.image_url }}"
                                            alt="Card image cap" style="height: 18rem;"></a>
                                    {% endif %}

                                    <div class="card-body p-6 text-center">
                                        <div class="Tags gap-xy-2 text-center mt-6">
                                            {% for category in post.categories.all %}
                                            <a href="#" class="badge badge-secondary text-uppercase">{{ category }}</a>
                                            {% endfor %}
                                        </div>
                                        <h5 class="card-title mb=0"><a class="text-dark" href="{{ post.post_link }}">{{ post.title }}</a></h5>
                                        <p>Author:&nbsp;{{ post.author }}</p>
                                        <p>
                                            Published on:&nbsp;{{ post.created_at|date }} | {% get_hit_count for post %}&nbsp;&nbsp;<i class="fas fa-eye" aria-hidden="true"></i>&nbsp;views
                                        </p>
                                    </div>
                                </div>
                                <br>
                            </div>
                            {% endfor %}

                            {% else %}
                            <h1 align="center">No post for this user yet...</h1>
                            {% endif %}
                            {% comment %} end for all the blog post of the current user {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'blog/pagination.html' %}
    {% include 'pages/footer.html' %}
</section>

{% endblock content %}

templates/pages/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- custom CSS-->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <!-- MDB -->
    <link rel="stylesheet" href='{% static "css/mdb.min.css" %}'/>

    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/f77049314d.js" crossorigin="anonymous"></script>

    <title>ShareItBlog{% block title %}{% endblock title %}</title>
</head>

<body>
    {% include 'pages/navbar.html' %}
    
    {% block content %}
    
    {% endblock content %}
    
    {% include 'pages/scripts.html' %}
</body>

</html>

templates/pages/change_password.html
{% extends 'pages/base.html' %}
{% load crispy_forms_tags %}

{% block title %} Change Password {% endblock %}

{% block content %}

<div class="d-flex align-items-center min-vh-100">
    <div class="container">
        {% if user.is_authenticated %}
        <div class="card border-primary">
            <div class="card-header">
                <h1>Change Password</h1>
            </div>

            <div class="card-body">
                <br>
                <div class="form-group">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-info btn-lg btn-block">Change Password</button>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/pages/footer.html
<section class="mt-5">
    {% if user.is_authenticated %}
    <footer class="text-center text-white" style="background-color: #0a4275;">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2021 Copyright:
            <a class="text-white" href="#">ShareItBlog.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    {% else %}
    <!-- Footer -->
    <footer class="text-center text-white" style="background-color: #0a4275;">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: CTA -->
            <section class="">
                <p class="d-flex justify-content-center align-items-center">
                    <span class="me-3">Register for free</span>
                    <a href="{% url 'account_signup' %}" type="button" class="btn btn-outline-light btn-rounded">
                        <strong>Sign up!</strong>
                    </a>
                </p>
            </section>
            <!-- Section: CTA -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2021 Copyright:
            <a class="text-white" href="#">ShareItBlog.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    {%endif%}
</section>

templates/pages/home.html
<!doctype html>
<html lang="en">
  {% include 'pages/head.html' %}
  <body>
    <h1>Hello, world!</h1>

    {% include 'pages/scripts.html' %}
  </body>
</html>

templates/pages/my_profile.html
{% extends 'pages/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load hitcount_tags %}

{% block title %} | My Profile{% endblock title %}

{% block content %}

<section class="h-100 gradient-custom-2">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-10 col-xl-10">
                <div class="card">
                    <div class="rounded-top text-white d-flex flex-row"z style="background-color: #000; height:200px;">
                        <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                            <img src="{{ profile.avatar.url }}" alt="Generic placeholder image"
                                class="img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">

                            <div class="d-flex justify-content-center mb-2">
                                {% if user.is_authenticated %}
                                <a href="{% url 'pages:update_profile' %}" type="button" class="btn btn-secondary"
                                    data-mdb-ripple-color="dark" style="z-index: 1;">
                                    Edit profile
                                </a>
                                {% endif %}
                            </div>

                        </div>
                        <div class="ms-3" style="margin-top: 130px;">
                            <h5>{{ profile.first_name }}&nbsp;{{ profile.middle_name }}&nbsp;{{ profile.last_name }}
                            </h5>
                            <p>{{ profile.user }}</p>
                        </div>
                    </div>
                    <div class="p-4 text-black" style="background-color: #f8f9fa;">
                        <div class="d-flex justify-content-end text-center py-1">
                            <div>
                                <p class="mb-1 h5">{{ posts_count }}</p>
                                <p class="small text-muted mb-0"># of Blog Posts</p>
                            </div>
                            <div class="px-3">
                                <p class="mb-1 h5">{{ comment_count }}</p>
                                <p class="small text-muted mb-0"># Comments</p>
                            </div>
                        </div>
                    </div>
                    <div class="card-body p-4 text-black">
                        <div class="mb-5">
                            <p class="lead fw-normal mb-1">About Me</p>
                            <div class="p-4" style="background-color: #f8f9fa;">
                                <p class="font-italic mb-1">{{ profile.bio }}</p>
                            </div>

                            <p class="lead fw-normal mb-1">Email Address</p>
                            <div class="p-4" style="background-color: #f8f9fa;">
                                <p class="font-italic mb-1">{{ profile.user.email }}</p>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mb-4">
                            <p class="lead fw-normal mb-0">My Blog Posts</p>
                        </div>
                        <div class="row g-2">
                            {% if posts %}
                            {% for post in posts %}
                            <div class="col-md-6">
                                <div
                                    class="card border hover-shadow-6 mb-6 d-block bg-image hover-overlay hover-zoom hover-shadow ripple">
                                    {% if post.thumbnail %}
                                    <a href="#"><img class="card-img-top" src="{{ post.thumbnail.url }}"
                                            alt="Card image cap" style="height: 18rem;"></a>
                                    {% else %}
                                    <a href="#"><img class="card-img-top" src="{{ post.image_url }}"
                                            alt="Card image cap" style="height: 18rem;"></a>
                                    {% endif %}

                                    <div class="card-body p-6 text-center">
                                        <div class="Tags gap-xy-2 text-center mt-6">
                                            {% for category in post.categories.all %}
                                            <a href="#" class="badge badge-secondary text-uppercase">{{ category }}</a>
                                            {% endfor %}
                                        </div>
                                        <h5 class="card-title mb=0"><a class="text-dark" href="{{ post.post_link }}">{{ post.title }}</a></h5>
                                        <p>Author:&nbsp;{{ post.author }}</p>
                                        <p>
                                            Published on:&nbsp;{{ post.created_at|date }} | {% get_hit_count for post %}&nbsp;&nbsp;<i class="fas fa-eye" aria-hidden="true"></i>&nbsp;views
                                        </p>
                                    </div>
                                </div>
                                <br>
                            </div>
                            {% endfor %}

                            {% else %}
                            <h1 align="center">No post for this user yet...</h1>
                            {% endif %}
                            {% comment %} end for all the blog post of the current user {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'blog/pagination.html' %}
    {% include 'pages/footer.html' %}
</section>

{% endblock content %}

templates/pages/myprofile_edit_form.html
{% extends 'pages/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} | Update Profile{% endblock title %}

{% block content %}

<section class="h-100 gradient-custom-2">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-10 col-xl-10">
                <div class="card">
                    <h1 class="card-title ml-5 mt-5">Edit Profile</h1>
                    <div class="bg-image hover-overlay hover-zoom hover-shadow ripple text-center">
                        <img class="img-fluid" style="height: 18rem;" src="{{ user.profile.avatar.url }}">
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(57, 192, 237, 0.2);"></div>
                        </a>
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset class="form-group">

                                {% if success %}
                                <div class="alert alert-info alert-dismissible fade show" role="alert">
                                    <strong>Your profile has been updated.</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% endif %}

                                {% if failed %}
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    <strong>Email already exist. Failed to update your profile.</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% endif %}

                                <legend class="border-bottom mb-4">Profile Info</legend>
                                {{ u_form|crispy }}
                                {{ p_form|crispy }}

                                <div class="form-group">
                                    <button class="btn btn-primary btn-block" type="submit">Update profile</button>
                                </div>
                            </fieldset>
                        </form>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'pages/footer.html' %}
</section>

{% endblock %}

templates/pages/navbar.html
{% load static %}

<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Container wrapper -->
    <div class="container-fluid">
        <!-- Toggle button -->
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
            data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Navbar brand -->
            {% url 'home' as home %}
            <a class="navbar-brand" href="#">
                <h3 class="display-6 text-muted">ShareItBlog</h3>
            </a>
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
                </li>
                {% url 'post_blog_page' as post_blog_page %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_blog_page' %}">Compose blog</a>
                </li>
            </ul>
            <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->
        {% if user.is_authenticated %}
        <!-- Right elements -->
        <div class="d-flex align-items-center">
            <p class="me-auto mb-2 mb-lg-0"><strong style="color: #08355E;">Hello, {{ user }}!</strong></p>
            
            <!-- Avatar -->
            <div class="dropdown ml-5 mr-4">
                <a class="dropdown-toggle d-flex align-items-center" href="#" id="navbarDropdownMenuAvatar"
                    role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                    <img class="avatar rounded-circle" height="40" alt="This is image..." loading="lazy" src="{{ request.user.profile.avatar.url }}">
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
                    {% url 'my_profile' as my_profile %}
                    <li><a class="dropdown-item" href="{% url 'pages:my_profile' %}">My Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'pages:change-password' %}">Change Password</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign Out</a></li>
                </ul>
            </div>
        </div>
        {% else %}
        <div class="d-flex align-items-center">
            <a type="button" class="btn btn-link px-3 me-2" href="{% url 'account_login' %}">
            Login
            </a>
            <a type="button" class="btn btn-primary me-3" href="{% url 'account_signup' %}">
            Sign up for free
            </a>
        </div>
        {% endif %}
        <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
</nav>
<!-- end of navbar -->

<!-- {% block mdb_js %}

{% endblock mdb_js %} -->

templates/pages/password_success.html
{% extends 'pages/base.html' %}

{% block title %} Password Change {% endblock %}

{% block content %}

<h1 align="center">Your Password Has Changed Successfully.</h1>

{% endblock %}

templates/pages/scripts.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- MDB -->
<script type="text/javascript" src='{% static "js/mdb.min.js" %}'></script>