blog/urls.py
from blog.views import PostDetailView, search, PostBlogView, UpdateBlogView, DeleteBlogView, CommentReplyView
from django.urls import path

urlpatterns = [
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post'),
    path('post/<int:post_pk>/comment/<int:pk>/reply', CommentReplyView.as_view(), name='reply'),
    path('post_blog_page/', PostBlogView.as_view(), name='post_blog_page'),
    path('post_blog_page/delete/<int:pk>', DeleteBlogView.as_view(), name='delete_blog_page'),
    path('post_blog_page/update/<int:pk>', UpdateBlogView.as_view(), name='update_blog_page'),
    path('q', search, name='search'),
]

pages/urls.py
from . import views
from django.conf.urls import url
from django.urls import path, re_path
from pages.views import author_profiles, ChangePassword, DevProfileView, home, my_profile, portfolio, update_profile

app_name = 'pages'

urlpatterns = [
    path('', home, name='home'),
    re_path(r'^author_profiles/(?P<id>[0-9]+)/$',
            author_profiles, name='author_profiles'),
    path('change-password/', ChangePassword.as_view(
        template_name='pages/change_password.html'), name='change-password'),
    path('my_profile/', my_profile, name='my_profile'),
    path('my_profile/update/', update_profile, name='update_profile'),
    path('password_success/', views.password_success, name='password_success'),
    path('developer_profile/', DevProfileView.as_view(), name='developer_profile'),
]

shareItBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path( 'admin/', admin.site.urls ),
    path( 'accounts/', include( 'allauth.urls' ) ),
    path( '', include( 'pages.urls', namespace='pages' ) ),
    path( '', include( 'blog.urls' ) ),
    path( 'ckeditor/', include( 'ckeditor_uploader.urls' ) ),
] 
# + static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT ) + static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )
    urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )

blog/models.py
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.shortcuts import reverse
from hitcount.models import HitCount
from taggit.managers import TaggableManager

User = get_user_model()

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=25)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = AutoSlugField(populate_from='title', unique=True)
    thumbnail = models.ImageField(
        default='default/default_blog_post_img1.png', upload_to='thumbnails/', blank=True, null=True)
    image_url = models.CharField(
        default=None, max_length=500, blank=True, null=True)
    content = RichTextField()
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts')
    categories = models.ManyToManyField(Category)
    hit_count_generic = GenericRelation(
        HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    tags = TaggableManager()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    @property
    def post_link(self):
        return reverse('post', kwargs={
            'slug': self.slug,
        })

    @staticmethod
    def get_absolute_url(self):
        return reverse('home')

    def __str__(self):
        return self.title + ' | ' + self.slug + ' | ' + str(self.author)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, blank=True, null=True, related_name='+')

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    @property
    def children(self):
        return Comment.objects.filter(parent=self).order_by('-created_at').all()

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False

    def __str__(self):
        return str('%s | %s' % (self.user.username, self.created_at.strftime('%d-%m-%Y')))

blog/forms.py
from blog.models import Comment, Post
from django import forms

# Create your forms here.


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='Leave a comment', widget=forms.Textarea(attrs={
        'class': 'md-textarea form-control mt-6',
        'placeholder': 'Comment here...',
        'rows': '4',
    }))

    class Meta:
        model = Comment
        fields = ('content',)


class UpdateBlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'author',
            'thumbnail',
            'image_url',
            'content',
            'categories',
            'tags',
        )

        widgets = {
            'author': forms.TextInput(
                attrs={'class': 'form-control', 'value': '', 'id': 'author_id', 'type': 'hidden'}),
        }


class PostBlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'author',
            'thumbnail',
            'image_url',
            'content',
            'categories',
            'tags',
        )

        widgets = {
            'author': forms.TextInput(
                attrs={'class': 'form-control', 'value': '', 'id': 'author_id', 'type': 'hidden'}),
        }


class ReplyForm(forms.ModelForm):
    content = forms.CharField(label='Leave a reply', widget=forms.Textarea(attrs={
        'class': 'md-textarea form-control mt-6',
        'placeholder': 'Reply here...',
        'rows': '4',
    }))

    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from blog.forms import CommentForm, PostBlogForm, UpdateBlogForm, ReplyForm
from blog.models import Post, Comment, Category
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView
from hitcount.views import HitCountDetailView
from pages.forms import Profile

# Create your views here.


def blog(request):
    posts = Post.objects.all()
    categories = Category.objects.all()
    popular_posts = Post.objects.order_by('hit_count_generic')[:4]

    popular_posts_head = Post.objects.order_by('hit_count_generic')[:1]

    page = request.GET.get('page')
    paginator = Paginator(posts, 9)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'categories': categories,
        'popular_posts': popular_posts,
        'popular_posts_head': popular_posts_head,
        'page': page,
    }
    return render(request, 'blog/blog.html', context)


def search(request):
    context = {}

    posts = Post.objects.all()
    categories = Category.objects.all()
    popular_posts = Post.objects.order_by('hit_count_generic')[:4]

    if request.method == "GET":
        query = request.GET.get('search')
        queryset = posts.filter(Q(title__icontains=query))

        page = request.GET.get('page')
        paginator = Paginator(queryset, 9)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        total = queryset.count()
        context.update({
            'posts': posts,
            'categories': categories,
            'popular_posts': popular_posts,
            'query': query,
            'page': page,
            'total': total,
        })

        return render(request, "blog/search-blog.html", context)


class CommentReplyView(LoginRequiredMixin, View):
    slug_field = 'slug'

    def post(self, request, post_pk, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=post_pk)
        parent_comment = get_object_or_404(Comment, pk=pk)
        form = ReplyForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post
            new_comment.parent = parent_comment
            new_comment.save()

            return redirect(reverse('post', kwargs={'slug': post.slug}))

        return redirect('post', pk=post_pk)


class DeleteBlogView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/post.html'
    success_url = reverse_lazy('pages:home')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.username == self.request.user:
            messages.warning(
                self.request, "You're not the author of this blog post...")
        return obj


class PostBlogView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostBlogForm
    template_name = 'blog/compose_blog.html'
    success_url = reverse_lazy('pages:home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PostDetailView(HitCountDetailView):
    model = Post
    template_name = 'blog/post.html'
    slug_field = 'slug'
    count_hit = True

    form1 = CommentForm
    form2 = ReplyForm

    def get_context_data(self, **kwargs):
        posts = Post.objects.all()
        similar_posts = self.object.tags.similar_objects()[:3]
        categories = Category.objects.all()
        popular_posts = Post.objects.order_by('hit_count_generic')[:4]

        profile = Profile.objects.all()
        post_comments = Comment.objects.all().filter(post=self.object.id)
        post_comments_count = Comment.objects.all().filter(post=self.object.id).count()
        context = super().get_context_data(**kwargs)

        context.update({
            'form1': self.form1,
            'form2': self.form2,
            'post_comments': post_comments,
            'post_comments_count': post_comments_count,
            'profile': profile,

            'posts': posts,
            'similar_posts': similar_posts,
            'categories': categories,
            'popular_posts': popular_posts,
        })
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = self.get_object()
            form.instance.user = request.user
            form.instance.post = post
            form.save()

            return redirect(reverse('post', kwargs={'slug': post.slug}))


class UpdateBlogView(UpdateView):
    model = Post
    form_class = UpdateBlogForm
    template_name = 'blog/update_blog.html'
    success_url = reverse_lazy('pages:home')

templates/blog/about.html
<div class="card mt-4">
    <div class="card-body bg-light">
        <h3 class="card-title">About</h3>
        <p class="card-text">
            <p class="mb-0"><strong>Hello, World!</strong></p><br>
            <p class="mb-0">My name is <a class="text-dark" href="{% url 'pages:developer_profile' %}"><strong style="color: green;">Joemar T. Greta.</strong></a>, I developed ShareItBlog for us to share the knowledge or
                stories we want to tell to others.
                I hope you'll enjoyed the sharing with respect and responsibility to your post.
            </p>
        </p>
    </div>
</div>

templates/blog/blog.html
{% include 'pages/base.html' %}

{% block content %}

<div class="mx-auto pt-2">
    {% include 'blog/header.html' %}
</div>

<main class="main-content">
    <div class="section bg-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-xl-8">
                    <!-- home posts -->
                    <div class="row gap-y">
                        {% include 'blog/home_posts.html' %}
                    </div>
                </div>
                <!-- side bar -->
                <div class="col-lg-4 col-xl-4 position-sticky">
                    <div class="card">
                        <!-- search -->
                        {% include 'blog/search.html' %}
                        <!-- categories -->
                        {% include 'blog/categories.html' %}
                        <!-- top blog -->
                        {% include 'blog/top_posts.html' %}
                        <!-- about -->
                        {% include 'blog/about.html' %}
                    </div>
                </div>
                <!-- end of side bar -->
            </div>
            <!-- pagination -->
            {% include 'blog/pagination.html' %}
        </div>
    </div>
</main>
{% include 'pages/footer.html' %}
{% endblock content %}

templates/blog/categories.html
<div class="card mt-4">
    <div class="card-body bg-light">
        <h3 class="card-title">Categories</h3>
        <p class="card-text">
            <div class="row link-color-default fs-14 lh-24">
                {% for category in categories %}
                <div class="col-6"><a href="#" class="badge badge-info text-uppercase">{{ category }}</a></div>
                {% endfor %}
            </div>
        </p>
    </div>
</div>

templates/blog/compose_blog.html
{% extends 'pages/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} | Compose{% endblock title %}

{% block content %}

<section class="h-100 gradient-custom-2">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-10 col-xl-10">
                <div class="card">
                    <div class="card-body">
                        <h1 class="card-title">Let's compose a blog</h1>
                        <p class="card-text">
                            {% if user.is_authenticated %}
                            <br><br>
                        <div class="form-group">
                            <form method="POST" action="" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.media|safe }}
                                {{ form|crispy }}
                                {% comment %} {% if user.is_authenticated %} {% endcomment %}
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Publish</button>
                                {% comment %} {% endif %} {% endcomment %}
                            </form>
                        </div>
                        <script>
                            var name = "{{ user.id }}";
                            document.getElementById("author_id").value = name;
                        </script>
                        {% else %}
                        <h1 align="center">Please <a href="{% url 'account_signup' %}" class="badge badge-info">Register</a> or
                            <a href="{% url 'account_login' %}" class="badge badge-info">Sign In</a> First...
                        </h1>
                        {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'pages/footer.html' %}
</section>

{% endblock %}

templates/blog/header-search-result.html
<header class="header text-white bg-dark d-grid gap-3 bg-light border-bottom mb-4 mt-1" style="min-height: 30rem;">
    <div class="container d-flex align-items-center justify-content-center">
        <div class="text-center my-5">
            <div class="col-md-8 mx-auto">
                <h1 class="display-6 font-italic">Search:&nbsp;{{ query }}</h1>
                <p class="lead-2 opacity-90 mt-6">{{ total }}Result(s) Found.</p>
            </div>
        </div>
    </div>
</header>

templates/blog/header.html
<header class="header text-white bg-dark d-grid gap-3 bg-light border-bottom mb-4 mt-1" style="min-height: 30rem;">
    <div class="container d-flex align-items-center justify-content-center">
        <div class="text-center my-5">
            {% for popular in popular_posts_head %}
            <div class="col-md-8 mx-auto">
                <h1 class="display-6 font-italic">{{ popular.title }}</h1>
                <p class="lead-2 opacity-90 mt-6">{{ popular.content|slice:":250"|safe }}<b>[...]</b></p>
                <a href="{{ popular.post_link }}" class="btn btn-lg btn-primary btn-rounded">Continue reading...&nbsp;&nbsp<i class="fas fa-arrow-right"></i></a>
            </div>
            {% endfor %}
        </div>
    </div>
</header>

templates/blog/home_posts.html
{% load hitcount_tags %}
{% load static %}

{% for post in posts %}
<div class="col-md-6">
    <div class="card border hover-shadow-6 mb-6 d-block bg-image">
        <div class="bg-image hover-overlay hover-zoom hover-shadow ripple">
            {% if post.thumbnail %}
            <img class="img-fluid" src="{{ post.thumbnail.url }}" style="height: 18rem; max-width: 100%;">
            <a href="#!">
                <div class="mask" style="background-color: rgba(57, 192, 237, 0.2);"></div>
            </a>
            {% else %}
            <img class="img-fluid" src="{{ post.image_url }}" style="height: 18rem; max-width: 100%;">
            <a href="#!">
                <div class="mask" style="background-color: rgba(57, 192, 237, 0.2);"></div>
            </a>
            {% endif %}
        </div>
        <div class="card-body">
            <div class="Tags gap-xy-2 mt-6">
                {% for category in post.categories.all %}
                <a href="#" class="badge badge-primary text-uppercase">{{ category }}</a>
                {% endfor %}
            </div>
            <h5 class="card-title"><strong>{{ post.title }}</strong></h5>
            <p>
                <img src="{{ post.author.profile.avatar.url }}" alt="" style="max-width:50px;max-height:50px;"
                    class="avatar rounded-pill img-fluid mr-3">Author:&nbsp;{{ post.author }}
            </p>
            <p class="text-muted">
                Published on:&nbsp;{{ post.created_at|date }} | {% get_hit_count for post %}&nbsp;&nbsp;<i
                    class="fas fa-eye" aria-hidden="true"></i>&nbsp;views
            </p>
            
            <p class="card-text">{{ post.content|slice:"250"|safe }}[...]</p>
            <a href="{{ post.post_link }}" class="btn btn-primary">Read more&nbsp;<i class="fas fa-arrow-right"></i></a>
        </div>
    </div>
</div>
{% endfor %}

templates/blog/pagination.html
<nav aria-label="Page navigation flexbox mt-10">
    <ul class="pagination justify-content-center">
        {% if posts.has_previous %}
        <li class="page-item mr-2">
            <a class="page-link" href="?page={{ posts.previous_page_number }}" tabindex="-1"><< Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled mr-2">
            <a class="page-link" href="#" tabindex="-1"><< Previous</a>
        </li>
        {% endif %}

        {% for i in posts.paginator.page_range %}
        {% if posts.number == i %}
        <li class="page-item active"><a class="page-link">{{ i }} <span class="sr-only">(current)</span></a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}

        {% if posts.has_next %}
        <li class="page-item ml-2">
            <a class="page-link" href="?page={{ posts.next_page_number }}">Next >></a>
        </li>
        {% else %}
        <li class="page-item disabled ml-2">
            <a class="page-link" href="#">Next >></a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/blog/search-blog.html
{% include "pages/base.html" %}

{% block content %}
<br><br>
{% include 'blog/header-search-result.html' %}

<main class="main-content">
    <div class="section bg-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-xl-8">
                    <!-- home posts -->
                    <div class="row gap-y">
                        {% include 'blog/home_posts.html' %}
                    </div>
                </div>
                <!-- side bar -->
                <div class="col-lg-4 col-xl-4 position-sticky">
                    <div class="card mb-6">
                        <!-- search -->
                        {% include 'blog/search.html' %}
                        <!-- categories -->
                        {% include 'blog/categories.html' %}
                        <!-- top blog -->
                        {% include 'blog/top_posts.html' %}
                        <!-- about -->
                        {% include 'blog/about.html' %}
                    </div>
                </div>
                <!-- end of side bar -->
            </div>
            <!-- pagination -->
            <div class="d-flex justify-content-center">
                <ul class="pagination">
                    {% if posts.has_previous %}
                    <li class="page-item"><a href="?search={{ query }}&page={{ posts.previous_page_number }}" class="page-link"><< Previews</a></li>
                    {% else %}
                    <li class="page-item disabled"><a href="#" class="page-link"><< Previews</a></li>
                    {% endif %}

                    {% if 3 in posts.paginator.page_range %}
                    {% if page|add:'-1' >= 1 %}
                    <li class="page-item"><a href="?search={{ query }}&page={{ page|add:'-1' }}" class="page-link"> {{ page|add:'-1' }} </a></li>
                    {% endif %}

                    <li class="page-item"><a href="?search={{ query }}&page={{ page }}" class="page-link"> {{ page }} </a></li>

                    {% if page|add:'1' in posts.paginator.page_range %}
                    <li class="page-item"><a href="?search={{ query }}&page={{ page|add:'1' }}" class="page-link"> {{ page|add:'1' }} </a></li>
                    {% endif %}

                    {% else %}
                    {% for number in posts.paginator.page_range %}
                    <li class="page-item"><a href="?search={{ query }}&page={{ number }}" class="page-link"> {{ number }} </a></li>
                    {% endfor %}
                    {% endif %}

                    {% if posts.has_next %}
                    <li class="page-item"><a href="?search={{ query }}&page={{ posts.next_page_number }}" class="page-link">Next >></a></li>
                    {% else %}
                    <li class="page-item disabled"><a href="#" class="page-link">Next >></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</main>
{% include 'pages/footer.html' %}
{% endblock content %}

templates/blog/search.html
<div class="card">
    <div class="card-body">
        <div class="input-group">
            <div class="form-outline">
                <form class="input-group" action="{% url 'search' %}" method="GET" role="form">
                    <input type="search" name="search" id="form1" class="form-control" />
                    <label class="form-label" for="form1">Search</label>
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-search">Go!</i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/blog/top_posts.html
<div class="card mt-4">
    <div class="card-body bg-light">
        <h3 class="card-title">Top Posts</h3>
        {% for popular in popular_posts %}
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    {% if popular.thumbnail %}
                    <img src="{{ popular.thumbnail.url }}" alt="popular-post-image" style="height: 80px; width: 80px;"
                        class="img-fluid rounded-start">
                    {% else %}
                    <img src="{{ popular.image_url }}" alt="popular-post-image" style="height: 80px; width: 80px;"
                        class="img-fluid rounded-start">
                    {% endif %}
                    </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="car-link"><a href="{{ popular.post_link }}">{{ popular.title }}</a></h5>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/blog/update_blog.html
{% extends 'pages/base.html' %}
{% load crispy_forms_tags %}

{% block title %} | Update{% endblock title %}

{% block content %}

<div class="container">
    {% if user.is_authenticated %}
    {% if user.id == post.author.id %}

    <h1>Update a Blog Post...</h1>
    <br><br>
    <div class="form-group">
        {% comment %} update form {% endcomment %}
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <button type="submit" class="btn btn-info btn-lg btn-block">Update Blog</button>
        </form>
        {% comment %} end of update form {% endcomment %}
    </div>

    {% else %}
    <h1 align="center">You're not the author of this blog post...</h1>
    {% endif %}

    {% else %}

    <h1 align="center">Please <a href="{% url 'account_signup' %}" class="badge badge-info">Register</a> or <a
            href="{% url 'account_login' %}" class="badge badge-info">Sign In</a> First...</h1>

    {% endif %}
</div>

{% endblock %}